config/routes.rb
Rails.application.routes.draw do
  root to: 'campaigns#index'
  resources :campaigns, only: [:index, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/campaign.rb
class Campaign < ApplicationRecord
  has_many :votes
  has_many :candidates, through: :votes
end

app/models/candidate.rb
class Candidate < ApplicationRecord
  has_many :votes
end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :campaign
  belongs_to :candidate
  
  enum validity: [:during, :pre, :post]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/campaigns_controller.rb
class CampaignsController < ApplicationController
  def index
    @campaigns = Campaign.all
  end
  
  def show
    @campaign = Campaign.find(params[:id])
    @candidates = @campaign.candidates.uniq
    @candidates_and_scores = {}
    
    @candidates.each do |candidate|
      @candidates_and_scores[candidate.name] = candidate.votes.where(campaign_id: @campaign.id, candidate_id: candidate.id).during.count
    end
    
    @candidates_and_scores = Hash[@candidates_and_scores.sort_by{|k,v| v}.reverse]
    @uncounted_votes = @campaign.votes.pre + @campaign.votes.post
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/campaigns/_campaign.html.erb
<%= link_to campaign.name, campaign_path(campaign) %>

app/views/campaigns/index.html.erb
<h2>Campaigns</h2>

<div class="tabular">
  <%= render @campaigns %>
</div>

app/views/campaigns/show.html.erb
<h2>Votes for campaign: <%= @campaign.name %></h2>

<div class="candidates">
  <% @candidates_and_scores.each do |name, votes| %>
    <p><%= name %></p>
    <p><%= votes %></p>
  <% end %>
</div>

<p>Uncounted votes: <%= @uncounted_votes.count %></p>

app/views/candidates/_candidate.html.erb
<p><%= candidate.name %></p>
<p><%= candidate.votes.during.count %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>VoteCounter</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
     <div class="container">
        <%= link_to root_path do %>
          <h1>Votes Counter</h1>
        <% end %>
        
        <%= yield %>
     </div>
  </body>
</html>